export enum EnvKeys {
  GH_USERNAME = 'GH_USERNAME',
  GH_TOKEN = 'GH_TOKEN',
  DO_REGISTRY_NAME = 'DO_REGISTRY_NAME',
  DO_API_TOKEN = 'DO_API_TOKEN',
  DO_SPACES_REGION = 'DO_SPACES_REGION',
  DO_SPACES_ACCESS_KEY = 'DO_SPACES_ACCESS_KEY',
  DO_SPACES_SECRET_KEY = 'DO_SPACES_SECRET_KEY',
  AMZ_ID = 'AMZ_ID',
  AMZ_SEC = 'AMZ_SEC',
  AMZ_REGION = 'AMZ_REGION',
}
